export const GROUPS = {
  marron:      { name: 'Marrón',      color: '#8B5A2B' },
  celeste:     { name: 'Celeste',     color: '#5BB9E6' },
  rosa:        { name: 'Rosa',        color: '#E56AA6' },
  naranja:     { name: 'Naranja',     color: '#F28C38' },
  roja:        { name: 'Roja',        color: '#D73A3A' },
  amarilla:    { name: 'Amarilla',    color: '#E0B93C' },
  verde:       { name: 'Verde',       color: '#2E8B57' },
  azulOscuro:  { name: 'Azul Oscuro', color: '#173E8F' },
};

// `code` = lo que se ve DENTRO de la casilla (3-4 letras, siempre legible sin zoom).
// `name` = lo que se ve en la tarjeta de detalle al tocar la casilla.
export const board = [
  { id: 0,  type: 'go', name: 'Salida', code: 'GO' },
  { id: 1,  type: 'property', name: 'Apopa Centro', code: 'APO', group: 'marron', price: 60, houseCost: 50 },
  { id: 2,  type: 'chest', name: 'Caja Comunal', code: 'CAJA' },
  { id: 3,  type: 'property', name: 'Ciudad Delgado Centro', code: 'CDG', group: 'marron', price: 60, houseCost: 50 },
  { id: 4,  type: 'tax', name: 'Renta Hacienda', code: 'HAC', amount: 200 },
  { id: 5,  type: 'railroad', name: 'Terminal de Occidente', code: 'TO-1', price: 200 },
  { id: 6,  type: 'property', name: 'Soyapango Centro', code: 'SOY', group: 'celeste', price: 100, houseCost: 50 },
  { id: 7,  type: 'chance', name: 'Suerte', code: 'SUER' },
  { id: 8,  type: 'property', name: 'Ilopango Centro', code: 'ILO', group: 'celeste', price: 100, houseCost: 50 },
  { id: 9,  type: 'property', name: 'Chalchuapa Centro', code: 'CHP', group: 'celeste', price: 120, houseCost: 50 },
  { id: 10, type: 'jail', name: 'Bartolinas', code: 'BART' },
  { id: 11, type: 'property', name: 'Centro Histórico de Sonsonate', code: 'SON', group: 'rosa', price: 140, houseCost: 100 },
  { id: 12, type: 'utility', name: 'AES El Salvador', code: 'AES', price: 150 },
  { id: 13, type: 'property', name: 'Centro Histórico de Santa Ana', code: 'STA', group: 'rosa', price: 140, houseCost: 100 },
  { id: 14, type: 'property', name: 'Centro Histórico de San Miguel', code: 'SMG', group: 'rosa', price: 160, houseCost: 100 },
  { id: 15, type: 'railroad', name: 'Terminal de Oriente', code: 'TE-1', price: 200 },
  { id: 16, type: 'property', name: 'Zaragoza', code: 'ZAR', group: 'naranja', price: 180, houseCost: 100 },
  { id: 17, type: 'chest', name: 'Caja Comunal', code: 'CAJA' },
  { id: 18, type: 'property', name: 'Lourdes Colón', code: 'LCO', group: 'naranja', price: 180, houseCost: 100 },
  { id: 19, type: 'property', name: 'Ciudad Merliot', code: 'MER', group: 'naranja', price: 200, houseCost: 100 },
  { id: 20, type: 'freeparking', name: 'Parqueo Gratis', code: 'PARK' },
  { id: 21, type: 'property', name: 'Santa Tecla Centro', code: 'STC', group: 'roja', price: 220, houseCost: 150 },
  { id: 22, type: 'chance', name: 'Suerte', code: 'SUER' },
  { id: 23, type: 'property', name: 'Colonia San Francisco', code: 'CSF', group: 'roja', price: 220, houseCost: 150 },
  { id: 24, type: 'property', name: 'Colonia Escalón', code: 'ESC', group: 'roja', price: 240, houseCost: 150 },
  { id: 25, type: 'railroad', name: 'Terminal del Sur', code: 'TS-1', price: 200 },
  { id: 26, type: 'property', name: 'Costa del Sol', code: 'CDS', group: 'amarilla', price: 260, houseCost: 150 },
  { id: 27, type: 'property', name: 'El Tunco', code: 'TUN', group: 'amarilla', price: 260, houseCost: 150 },
  { id: 28, type: 'utility', name: 'ANDA', code: 'ANDA', price: 150 },
  { id: 29, type: 'property', name: 'El Sunzal', code: 'SUN', group: 'amarilla', price: 280, houseCost: 150 },
  { id: 30, type: 'gotojail', name: 'Capturado en Régimen de Excepción', code: 'CAP' },
  { id: 31, type: 'property', name: 'San Benito', code: 'SBT', group: 'verde', price: 300, houseCost: 200 },
  { id: 32, type: 'property', name: 'Santa Elena', code: 'SEL', group: 'verde', price: 300, houseCost: 200 },
  { id: 33, type: 'chest', name: 'Caja Comunal', code: 'CAJA' },
  { id: 34, type: 'property', name: 'Cumbres de Cuscatlán', code: 'CUM', group: 'verde', price: 320, houseCost: 200 },
  { id: 35, type: 'railroad', name: 'Aeropuerto Internacional de El Salvador', code: 'AIES', price: 200 },
  { id: 36, type: 'chance', name: 'Suerte', code: 'SUER' },
  { id: 37, type: 'property', name: 'Tuscania', code: 'TUS', group: 'azulOscuro', price: 350, houseCost: 200 },
  { id: 38, type: 'tax', name: 'Impuesto de Alcaldía', code: 'ALC', amount: 100 },
  { id: 39, type: 'property', name: 'El Encanto', code: 'ENC', group: 'azulOscuro', price: 400, houseCost: 200 },
];
