export const GROUPS = {
  ahuachapan:   { name: 'Ahuachapán',   color: '#8B5A2B' },
  laLibertad:   { name: 'La Libertad',  color: '#2F9C95' },
  chalatenango: { name: 'Chalatenango', color: '#D98E3B' },
  cabañas:      { name: 'Cabañas',      color: '#C1502E' },
  sanSalvador:  { name: 'San Salvador', color: '#B5322E' },
  laPaz:        { name: 'La Paz',       color: '#E0B93C' },
  usulutan:     { name: 'Usulután',     color: '#2E7D46' },
  morazan:      { name: 'Morazán',      color: '#2B4C7E' },
};

export const board = [
  { id: 0,  type: 'go', name: 'Salida' },
  { id: 1,  type: 'property', name: 'Tacuba', group: 'ahuachapan', price: 60, houseCost: 50 },
  { id: 2,  type: 'chest', name: 'Caja Comunal' },
  { id: 3,  type: 'property', name: 'Concepción de Ataco', group: 'ahuachapan', price: 60, houseCost: 50 },
  { id: 4,  type: 'tax', name: 'Renta ANDA', amount: 200 },
  { id: 5,  type: 'railroad', name: 'Terminal de Occidente', price: 200 },
  { id: 6,  type: 'property', name: 'El Tunco', group: 'laLibertad', price: 100, houseCost: 50 },
  { id: 7,  type: 'chance', name: 'Suerte' },
  { id: 8,  type: 'property', name: 'La Libertad Centro', group: 'laLibertad', price: 100, houseCost: 50 },
  { id: 9,  type: 'property', name: 'Zunzal', group: 'laLibertad', price: 120, houseCost: 50 },
  { id: 10, type: 'jail', name: 'Cárcel' },
  { id: 11, type: 'property', name: 'La Palma', group: 'chalatenango', price: 140, houseCost: 100 },
  { id: 12, type: 'utility', name: 'CAESS', price: 150 },
  { id: 13, type: 'property', name: 'Suchitoto', group: 'chalatenango', price: 140, houseCost: 100 },
  { id: 14, type: 'property', name: 'El Poy', group: 'chalatenango', price: 160, houseCost: 100 },
  { id: 15, type: 'railroad', name: 'Terminal de Occidente Norte', price: 200 },
  { id: 16, type: 'property', name: 'Sensuntepeque', group: 'cabañas', price: 180, houseCost: 100 },
  { id: 17, type: 'chest', name: 'Caja Comunal' },
  { id: 18, type: 'property', name: 'Ilobasco', group: 'cabañas', price: 180, houseCost: 100 },
  { id: 19, type: 'property', name: 'Victoria', group: 'cabañas', price: 200, houseCost: 100 },
  { id: 20, type: 'freeparking', name: 'Parqueo Gratis' },
  { id: 21, type: 'property', name: 'Centro Histórico SS', group: 'sanSalvador', price: 220, houseCost: 150 },
  { id: 22, type: 'chance', name: 'Suerte' },
  { id: 23, type: 'property', name: 'Santa Tecla', group: 'sanSalvador', price: 220, houseCost: 150 },
  { id: 24, type: 'property', name: 'Zona Rosa', group: 'sanSalvador', price: 240, houseCost: 150 },
  { id: 25, type: 'railroad', name: 'Terminal de Oriente', price: 200 },
  { id: 26, type: 'property', name: 'Zacatecoluca', group: 'laPaz', price: 260, houseCost: 150 },
  { id: 27, type: 'property', name: 'Costa del Sol', group: 'laPaz', price: 260, houseCost: 150 },
  { id: 28, type: 'utility', name: 'ANDA', price: 150 },
  { id: 29, type: 'property', name: 'San Juan Nonualco', group: 'laPaz', price: 280, houseCost: 150 },
  { id: 30, type: 'gotojail', name: 'Ve a la Cárcel' },
  { id: 31, type: 'property', name: 'Usulután Centro', group: 'usulutan', price: 300, houseCost: 200 },
  { id: 32, type: 'property', name: 'Laguna de Alegría', group: 'usulutan', price: 300, houseCost: 200 },
  { id: 33, type: 'chest', name: 'Caja Comunal' },
  { id: 34, type: 'property', name: 'Bahía de Jiquilisco', group: 'usulutan', price: 320, houseCost: 200 },
  { id: 35, type: 'railroad', name: 'Terminal de Oriente Sur', price: 200 },
  { id: 36, type: 'chance', name: 'Suerte' },
  { id: 37, type: 'property', name: 'Perquín', group: 'morazan', price: 350, houseCost: 200 },
  { id: 38, type: 'tax', name: 'Impuesto de Alcaldía', amount: 100 },
  { id: 39, type: 'property', name: 'San Francisco Gotera', group: 'morazan', price: 400, houseCost: 200 },
];
